# Generated by Django 3.2.14 on 2022-08-01 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberBlocked',
            new_name='UserBlocked',
        ),
    ]
