# Generated by Django 3.2.14 on 2022-08-02 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20220801_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user_management.userlavel'),
        ),
    ]
