# Generated by Django 3.2.14 on 2022-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privider_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
