# Generated by Django 3.2.14 on 2022-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20220803_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privider_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signid_in_through',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
