# Generated by Django 3.2.14 on 2022-08-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20220803_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hometown',
            new_name='location',
        ),
    ]
