# Generated by Django 3.2.14 on 2022-12-01 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20221201_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan_verification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 2, 0, 3, 47, 608003), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inactive_till',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 0, 3, 47, 608003)),
        ),
    ]
