# Generated by Django 3.2.14 on 2022-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_name', models.CharField(max_length=120)),
                ('coin_image', models.ImageField(upload_to='upload/products/coin')),
                ('coin_rate', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diamond_name', models.CharField(max_length=120)),
                ('diamond_image', models.ImageField(upload_to='upload/products/diamond')),
                ('diamond_rate', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_name', models.CharField(max_length=120)),
                ('gift_image', models.ImageField(upload_to='upload/products/gift')),
                ('gift_rate', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='product_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='number_in_bundle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(choices=[('coin', 'Coin'), ('gift', 'Gift'), ('diamond', 'Diamond')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
