# Generated by Django 3.2.14 on 2022-08-06 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220804_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diamond',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserGiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_purchased', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('gift_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coin')),
                ('user_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDiamondPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_purchased', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('diamond_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coin')),
                ('user_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_purchased', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('coin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coin')),
                ('user_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
