# Generated by Django 3.2.14 on 2022-08-06 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20220806_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='gift_rate',
            new_name='gift_rate_diamond',
        ),
        migrations.CreateModel(
            name='UserAssetsReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_coin_purchased', models.IntegerField(default=0)),
                ('available_coins', models.IntegerField(default=0)),
                ('total_diamonds_purchased', models.IntegerField(default=0)),
                ('available_diamonds', models.IntegerField(default=0)),
                ('total_gifts_purchased', models.IntegerField(default=0)),
                ('available_gift', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
